### PR TITLE
Akash's contribution

### PR DESCRIPTION
**Pull request by Akash-1gif**
Wrote an article containing the basics of OS

### CODE REVIEW

**Comment by Axe-Pearl** [comment]
Hey @Akash-1gif, You really did nice work, it's really impressive.
Inform me of your increased pull request.
**Thanks**

**Comment by Akash-1gif** [comment]
Hey @Axe-Pearl my PR was not accepted in my hacktoberfest account. Please look into it

**Comment by Axe-Pearl** [comment]
Hey @Akash-1gif, What it's showing then

**Comment by Akash-1gif** [comment]
@Axe-Pearl it shows the following:

YOUR PR/MR HAS NOT YET BEEN ACCEPTED BY A MAINTAINER OF THE REPOSITORY. TO BE ACCEPTED, A MAINTAINER EITHER NEEDS TO MERGE YOUR PR/MR, ADD THE HACKTOBERFEST-ACCEPTED LABEL, OR LEAVE AN OVERALL APPROVING REVIEW.

FOR MORE INFORMATION ABOUT HOW EXACTLY WE VALIDATE PR/MRS FOR CONTRIBUTORS, CHECK THE DETAILS ON OUR PARTICIPATION PAGE.

**Comment by Axe-Pearl** [comment]
@Akash-1gif, It takes time to get updated on the profile.
When it will be accepted, inform me

**Comment by Akash-1gif** [comment]
> @Akash-1gif, It takes time to get updated on the profile.
> When it will be accepted, inform me

Yes @Axe-Pearl I just got to know. My PR got accepted now. Thank you!

**Comment by Axe-Pearl** [comment]
Hey @Akash-1gif , Thanks for your efforts and impressive contribution.

**Pull request merged**
