### PR TITLE
First contribution

### PR DESCRIPTION
**Pull request by Akash-1gif**
First contribution by Akash-1gif

### CODE REVIEW

**Comment by Axe-Pearl** [comment]
Hey @Akash-1gif, Thanks for your contribution. Merged your pull request.

**Comment by Axe-Pearl** [comment]
Hey @Akash-1gif, can you check and tell did you got a pull request on your profile

**Comment by Akash-1gif** [comment]
> Hey @Akash-1gif, can you check and tell did you got a pull request on your profile
Hey @Axe-Pearl, I'm sorry but I haven't received any pull request

**Comment by Axe-Pearl** [comment]
@Akash-1gif , I mean that check you got PR on the Hacktoberfest Profile or not

**Comment by Akash-1gif** [comment]
> @Akash-1gif , I mean that check you got PR on the Hacktoberfest Profile or not

Okay. Yes, I did get a PR in my Hacktoberfest profile. Thank you

**Pull request merged**
